[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "24WRmbtoMBRMyo1mYcsDFKLzJ7KyqgJqp5urh6vnYv8J"
counter = "HPeVb59xsfeFCBG6ags7jWdbVh3yFcBVaCcVjUJDg95D"
devolt_optimized = "9JnB7ngU6zY2JKi2fEGgioaiHxaS9NdkAXWcuT7RtLkS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
